### ISSUE TITLE
Pester Configuration

### ISSUE THREAD

**Issue by codaamok** [zyborg/pester-tests-report#17]
Hey, do you know if it's possible to use Pester Configuration options with the Action? https://pester-docs.netlify.app/docs/usage/configuration

**Comment by ebekker** [comment]
It is possible to use a Pester Configuration, but not directly with this Action.  That is, there is a general "catch all" approach to customize the way Pester tests are invoked -- instead of having the Action invoke your tests, you can invoke them directly any way you want and simply produce a test results output file before calling this Action, and then feed that into the Action as input.

Specifically, the [`test_results_path`](https://github.com/zyborg/pester-tests-report#inputs) input allows you specify the results output file of a Pester test run.  When this input is specified, this Action will _not_ invoke the Pester tests for you.  So all you need to do is invoke your Pester tests and make sure you generate results file in results file using NUnit 2.5 format.

For example, in the PesterConfiguration object you should provide a value of `NUnit2.5` for the `TestResult.OutputFormat` option and provide some path to generate test results for the `TestResult.OutputPath` option.  Then when you invoke this Action, simply provide the same path for the `test_results_path` input.
