### ISSUE TITLE
Test Result Report Attaching To Incorrect Workflow Run

### ISSUE THREAD

**Issue by stevexiong-hennepin** [zyborg/pester-tests-report#20]
I have a dev test workflow with over 234 workflow runs. New workflow runs will not add the test result report to its current workflow run . Instead, it adds all new test result reports to this some 234 workflow run. In other words, this 234 workflow run has all new test result reports attached to it. I confirmed this by deleting workflow runs to have a total of 233 workflow runs, executed two more runs, verified there was no issue on the 234 run, and the issue occurs on 235 run and so on.

**Comment by gerardog** [comment]
I have the same problem at https://github.com/gerardog/gsudo/tree/master/.github/workflows
- When I merge to master, it triggers a `ci.yml` workflow run # 1 with its Test Job, which properly uploads 'pester-test-reports'.
- Then I create a tag which triggers `release.yml` workflow run # 2. This wkf calls `ci.yml` ( `jobs.build.uses: ./.github/workflows/ci.yml`). The reports are uploaded to # 1 instead of # 2.

Feel free to fork gerardog/gsudo, edit the readme.md on master to trigger `ci`, then create a release with tag on the new commit, and you will see the problem.

**Comment by natescherer** [comment]
Ran into this myself, discovered this is actually a limitation in how check runs work. This is a limitation of how check runs work, check runs are attached to specific commits, not workflow runs: https://docs.github.com/en/rest/checks/runs

So if your workflow trigger isn't something that also changes the commit, there's no way for the check run to show up on that workflow. Kinda sucks but there's no working around this without major changes from GitHub.

FWIW, I added #23 which will block check run updates for workflow_dispatch and throw a notice about it.
